version: '3.8'
name: home-hub
services:
  
  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    expose:
      - '5173'
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      VIRTUAL_HOST: ${APP_DOMAIN}
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: ${APP_DOMAIN}
      VIRTUAL_ROOT: /usr/share/nginx/html
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - net

  #Nginx
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./docker/nginx/location_override.conf:/etc/nginx/vhost.d/${APP_DOMAIN}_location_override
      - ./docker/nginx/default.conf:/etc/nginx/vhost.d/${APP_DOMAIN}
      - ./docker/nginx/phpmyadmin/default.conf:/etc/nginx/vhost.d/${PHPMYADMIN_DOMAIN}
      - ./docker/nginx/phpmyadmin/location_override.conf:/etc/nginx/vhost.d/${PHPMYADMIN_DOMAIN}_location_override
    labels:
    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - net

  dockergen:
    image: nginxproxy/docker-gen:0.11
    container_name: nginx-proxy-gen
    restart: unless-stopped
    depends_on:
      - nginx
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - net
   
  #MySQL
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_FORWARD_PORT}:3306
    environment:
      MYSQL_DATABASE: home-hub
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Europe/Paris'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - /home/arnaud/dev/backup:/backup/familyhub
    networks:
      - net

  # phpmyadmin GUI for mysql     
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    container_name: phpmyadmin
    expose:
      - 80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      VIRTUAL_HOST: ${PHPMYADMIN_DOMAIN}
      LETSENCRYPT_HOST: ${PHPMYADMIN_DOMAIN}
    depends_on:
      - mysql
    networks:
      - net

#Networks
networks:
  net:
    driver: bridge

#Volumes
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  dbdata:
    driver: local